config/routes.rb
Rails.application.routes.draw do

  # resources :tasks

  # READ

  get "tasks", to: "tasks#index", as: :tasks

  get "task/:id", to: "tasks#show", as: :task

  # NEW TASK

  get "tasks/new", to: "tasks#new", as: :new_task

  post "tasks", to: "tasks#create", as: :create_task

  # EDIT TASK

  get "task/:id/edit", to: "tasks#edit", as: :task_edit

  patch "task/:id", to: "tasks#update", as: :task_update

  # EDIT DELETE
  delete "task/:id", to: "tasks#destroy", as: :delete_task


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new

  end

  def create
    @task = Task.new(user_params)
    @task.save

    redirect_to tasks_path
  end

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(user_params)

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end


  private

  def user_params
    params.require(:task).permit(:title, :details)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :class => 'form-control input' %>

  <%= f.label :details %>

    <%= f.text_field :details, :class => 'form-control input' %>

  <%= f.submit :class => 'btn btn-primary' %>

<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<form>
<% @tasks.each do |task| %>
<p>
<input type="checkbox" name="vehicle" value="Bike" class="checkbox">

<%= link_to task.title, task_path(task[:id]), :class => "my_link" %>

<%= link_to "", delete_task_path(task.id), :class => "fa fa-trash", method: :delete %>
</p>
<% end %>
</form>


<hr>

<p>
<i class="fa fa-plus" aria-hidden="true"></i>
<%= link_to "Add a new task", new_task_path %>
</p>

app/views/tasks/new.html.erb
<h1>Add a task</h1>

<form action="/tasks" method="post" class="form-inline my_form add_form">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input class="form-control input" type="text" name="task[title]" placeholder="Task title" id="title">
  <input class="form-control input" type="text" name="task[details]" placeholder="Task details" id="details">
  <input class="btn btn-primary" type="submit" value="Add task">
</form>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<hr>
<h3>Details</h3>
<p><%= @task.details %></p>

<div class="button_show btn-primary btn">
  <i class="fa fa-cog fa-spin" aria-hidden="true"></i>
  <%= link_to "Edit this task", task_edit_path %>
</div>
<hr>
  <div class="button_show btn-primary btn">
  <%= link_to "Return to tasks", tasks_path %>
</div>